[package]
name = "RustRestrictedIntegers"
version = "0.1.0"
authors = ["Jimmy Pace <jpace121@gmail.com>"]
repository = "https://github.com/jpace121/RustRestrictedIntegers"
readme = "README.md"
license = "MIT/Apache-2.0"
description = """Integral types with restricted ranges. Think ada."""
